config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/development_rates/:id/edit' => 'development_rates#edit'
  post '/development_rates/:id' => 'development_rates#show'
  resources :topics
  resources :coinrates
  resources :exchanges
  resources :rate_registers
  resources :development_rates
  resources :rates

  resources :countries

  get '/articles/suggested/:id/authorize' => 'articles#authorize'
  get '/articles/suggested/:id/deauthorize' => 'articles#deauthorize'
  get '/articles/suggested' => 'articles#suggested'
  get '/about_us' => 'home#about_us'
  get '/denial' => 'home#denial'

  get '/contact_us' => 'home#contact_us'

  get '/users/show' => 'admin#show'
  get '/users/all'=>'admin#alluser'
  get '/show_user/:id' => 'admin#show_user'
  devise_for :users
  resources :ratetypes
  resources :comments
  resources :rateclasses

  resources :companies
  resources :articles

  get '/new_article' => 'articles#new'
  get '/new_rate' => 'rateclasses#new_rate'
  get '/new_rate' => 'ratetypes#new_rate'
  get '/articles' => 'articles#index'
  get '/articles/:id/comments/new' => 'comments#new'

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
	validates :ratetype,:saleprice,:to_date, presence: true
  belongs_to :ratetype
  belongs_to :rateclass
  
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]

  # GET /exchanges
  # GET /exchanges.json
  def index
    @flag=false
    @element=""
     if params[:search]
      @element=params[:search]
      @flag=true
      @coinrates= Coinrate.joins([:ratetype]).where("name LIKE ? ", "#{params[:search]}%").order(todate: :desc).paginate(:page => params[:page], :per_page => 8)
      @exchanges = Exchange.joins([:ratetype]).where("name LIKE ? ", "#{params[:search]}%").order(to_date: :desc).paginate(:page => params[:page], :per_page => 8)
    else
      @flag=false
      @exchanges = Exchange.all.order(to_date: :desc).paginate(:page => params[:page], :per_page => 8)
      @coinrates= Coinrate.all.order(todate: :desc).paginate(:page => params[:page], :per_page => 8)
    end
  end

  # GET /exchanges/1
  # GET /exchanges/1.json
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
    @coinrate= Coinrate.new
    @id_moneda=""
    @rateclasses=Rateclass.all
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  # POST /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to exchanges_path, notice: 'La cotizacion de elemento se creó con exito. ' }
        format.json { render :show, status: :created, location: @exchange }
      else

        format.html { render :edit }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1
  # PATCH/PUT /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to exchanges_path, notice: 'La cotizacion de elemento se modificó con exito.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  # DELETE /exchanges/1.json
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: 'La cotizacion de elemento se eliminó con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_params
      params.require(:exchange).permit(:to_date, :buy_value, :ratetype_id, :rateclass_id, :coin, :saleprice)
    end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<ul class="nav nav-pills">

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Clases <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Crear Clase', new_rateclass_path %></li>
        <li><%= link_to 'Ver Clases', rateclasses_path %></li>


    </ul>

  </li>
   <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Tipos <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Crear Tipo', new_ratetype_path %></li>
        <li><%= link_to 'Ver Tipos', ratetypes_path %></li>


    </ul>

  </li>

</ul>




<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Cotización de Elemento</h1>





<% @rateclasses.each do |rateclass| %>
 <% if rateclass.name == "moneda" %>
 <% @id_moneda= rateclass.id %>
 <% end %>

<% end %>













<%= form_for(@exchange) do |f| %>

  <div class="row">
    <div class="container-fluid">
      <div class="col-xs-6">
        <p class='text-muted'>
          Rellene los siguientes campos con la información pertinente:<br>
        </p>
      </div>
      <div class="col-xs-6">
        <p class='text-muted' style="color:#D46A6A;" align="right">
          <i><small>Los campos marcados con (*) son obligatorios.</small>
          <br><br></i>
        </p>
      </div>
    </div>
    </div>

    <div class='row'>
      <div class="container-fluid" style="margin-left:6%; margin-right:6%;">
        <div class='row'>
         <p class='text-muted'>


            <%= f.label :a_la_fecha %>* <br>
            <%= f.date_select :to_date,:default => Time.now ,:order => [:day,:month,:year]%>


         </p>
        </div>
       <br><br>
        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :Precio_de_venta %>*<br>
    <%= f. number_field :saleprice, :class => 'text_field', :step => 'any' %>

          </p>
          </div>
        </div>


        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :moneda %>*<br>
    <%= f.select :coin, ['Bs.', 'USD']%>

          </p>
          </div>
        </div>
        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :tipo_de_elemento %>*<br>
     <%= f.collection_select(:ratetype_id, Ratetype.where("rateclass_id != ?", @id_moneda), :id, :name, {:required => "required"}) %>

   


            </p>
          </div>
        </div>








      </div>
    </div>
    <br>
    <br>
        <center>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>


  </div>
</center>
<% end %>


<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Cotización de Moneda</h1>


<div class="row">
    <div class="container-fluid">
      <div class="col-xs-6">
        <p class='text-muted'>
          Rellene los siguientes campos con la información pertinente:<br>
        </p>
      </div>
      <div class="col-xs-6">
        <p class='text-muted' style="color:#D46A6A;" align="right">
          <i><small>Los campos marcados con (*) son obligatorios.</small>
          <br><br></i>
        </p>
      </div>
    </div>
    </div>
<%= form_for(@coinrate) do |f| %>
  <% if @coinrate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coinrate.errors.count, "error") %> prohibited this coinrate from being saved:</h2>

      <ul>
      <% @coinrate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="container-fluid" style="margin-left:6%; margin-right:6%;">
  <div class='row'>
         <p class='text-muted'>


            <%= f.label :a_la_fecha %>* <br>
            <%= f.date_select :todate,:default => Time.now ,:order => [:day,:month,:year]%>


         </p>
  </div>

 <br>
 <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :Precio_de_venta %>*<br>
    <%= f. number_field :sale, :class => 'text_field', :step => 'any' %>Bs.

          </p>
          </div>
        </div>

  <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :Precio_de_compra %>*<br>
    <%= f. number_field :buy, :class => 'text_field', :step => 'any' %>Bs.

          </p>
          </div>
        </div>
 <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>






    <%= f.label :moneda %>*<br>
     <%= f.collection_select(:ratetype_id, Ratetype.where("rateclass_id = ?", @id_moneda), :id, :name, {:required => "required"}) %>


            </p>
          </div>
        </div>
  <br><br><br><br>
  </div>
 <center>
  <div class="actions">
     <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>
  </div>
</center>
<% end %>

<%= link_to 'Atras', :back, :class=>'btn btn-sm btn-default' %>

app/views/exchanges/edit.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Editar Cotización de Elemento</h1>
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h4>¡Oops! Algo pasó mientras guardabamos la información:</h4>

      <ul>
      <% @exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="container-fluid">
      <div class="col-xs-6">
        <p class='text-muted'>
          Rellene los siguientes campos con la información pertinente:<br>
        </p>
      </div>
      <div class="col-xs-6">
        <p class='text-muted' style="color:#D46A6A;" align="right">
          <i><small>Los campos marcados con (*) son obligatorios.</small>
          <br><br></i>
        </p>
      </div>
    </div>
    </div>

    <div class='row'>
      <div class="container-fluid" style="margin-left:6%; margin-right:6%;">
        <div class='row'>
         <p class='text-muted'>


            <%= f.label :a_la_fecha %>* <br>
            <%= f.date_select :to_date,:default => Time.now %>


         </p>
        </div>
       <br><br>
        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :Precio_de_venta %>*<br>
    <%= f. number_field :saleprice, :class => 'text_field', :step => 'any' %>

          </p>
          </div>
        </div>


        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :moneda %>*<br>
    <%= f.select :coin, ['Bs.', 'USD']%>
          </p>
          </div>
        </div>
        <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>
    <%= f.label :tipo_de_elemento %>*<br>
     <%= f.collection_select(:ratetype_id, Ratetype.all, :id, :name, {:required => "required"}) %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
        <center>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>     
  </div>
</center>
<% end %>

app/views/exchanges/fix.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Cotización de Moneda</h1>


<div class="row">
    <div class="container-fluid">
      <div class="col-xs-6">
        <p class='text-muted'>
          Rellene los siguientes campos con la información pertinente:<br>
        </p>
      </div>
      <div class="col-xs-6">
        <p class='text-muted' style="color:#D46A6A;" align="right">
          <i><small>Los campos marcados con (*) son obligatorios.</small>
          <br><br></i>
        </p>
      </div>
    </div>
    </div>
<%= form_for(@coinrate) do |f| %>
  <% if @coinrate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coinrate.errors.count, "error") %> prohibited this coinrate from being saved:</h2>
      <ul>
      <% @coinrate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="container-fluid" style="margin-left:6%; margin-right:6%;">
  <div class='row'>
         <p class='text-muted'>
            <%= f.label :a_la_fecha %>* <br>
            <%= f.date_select :todate,:default => Time.now %>
         </p>
  </div>

 <br>
 <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>
    <%= f.label :Precio_de_venta %>*<br>
    <%= f. number_field :sale, :class => 'text_field', :step => 'any' %>Bs.

          </p>
          </div>
        </div>

  <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>

    <%= f.label :Precio_de_compra %>*<br>
    <%= f. number_field :buy, :class => 'text_field', :step => 'any' %>Bs.

          </p>
          </div>
        </div>
 <div class='col-md-4'>
          <div class="field">
            <p class='text-muted'>


<% @rateclasses.each do |rateclass| %>
 <% if rateclass.name == "moneda" %>
 <% @id_moneda= rateclass.id %>
 <% end %>
<% end %>
    <%= f.label :moneda %>*<br>
     <%= f.collection_select(:ratetype_id, Ratetype.where("rateclass_id =" + @id_moneda.to_s), :id, :name, {:required => "required"}) %>


            </p>
          </div>
        </div>
  <br><br><br><br>
  </div>
 <center>
  <div class="actions">
     <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>
  </div>
</center>
<% end %>

app/views/exchanges/index.html.erb
 <h1 style=" border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Cotizaciones</h1>
 <div class="container-fluid" style="margin-left:1%; margin-right:1%;">


<%= form_tag(exchanges_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Buscar cotizacion" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn btn-sm" type="submit">Buscar</button>
    </div>
  <% end %>
  </div>


<div class="container-fluid" style="margin-left:1%; margin-right:1%;">
<!--PREGUNTAMOS SI HAY BUSQUEDA-->
<%if @flag %>
 <%if @exchanges.count ==0%>
<center><h2 style="color: #2D6F96;">Sin registros de <%=@element%></h2></center>
  <% else %>
<!--hasta PREGUNTAMOS SI HAY BUSQUEDA-->
<center><h2 style="color: #2D6F96;">Cotización de <%=@element%></h2></center>
  <% end %>

  <% end %>
<!--esto si es que no hay una busqueda-->

<%if @flag==false %>

<h2 style="color: #2D6F96;">Cotización de elementos</h2>
 <%if @exchanges.count ==0%>
      <center>
        <p class='text-muted'>No hay registros </p>
      </center>
  <%end%>

<% end %>

 <%if @exchanges.count > 0%>

  </div>

 <div class="container-fluid" style="margin-left:15%; margin-right:15%;">
    <center>
    <table class="table table-striped">
      <col width="20%">
      <col width="10%">
      <col width="10%">
       <col width="10%">
       <col width="10%">
       <col width="40%">

      <thead>
        <tr>
          <th>A la fecha</th>

          <th>Tipo</th>
             <th>Unidad</th>
      <th>Venta</th>
      <th>Moneda</th>


      <%if user_signed_in?%>
       <%if current_user.has_role? :admin%>

      <th >Opciones</th>
      <%end%>
  <%end%>
        </tr>
      </thead>

      <tbody>
        <% @exchanges.each do |exchange| %>
          <tr>

            <td><%= exchange.to_date %></td>


        <td><%= exchange.ratetype.name %></td>
        <td>1 <%= exchange.ratetype.unit %></td>

        <td><%= exchange.saleprice %></td>
         <td><%= exchange.coin %></td>
         <%if user_signed_in?%>
       <%if current_user.has_role? :admin%>
            <td>
              <div class='btn btn-group'>
                <%= link_to 'Editar', edit_exchange_path(exchange), class:'btn btn-xs btn-primary' %>
                <%= link_to 'Eliminar', exchange, method: :delete, data: { confirm: '¿Está seguro de eliminar?' } , class:'btn btn-xs btn-danger'%>

              </div>
            </td>
            <%end%>
            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>
         <%= will_paginate @exchanges, renderer: BootstrapPagination::Rails, :previous_label => '<i class="fa fa-arrow-left fa-fw"> </i>', :next_label => '<i class="fa fa-arrow-right fa-fw"> </i>' %><br>
<%end%>
    <br>
   <!--HASTA esto si es que no hay una busqueda-->
</div>
<!--esto si es que no hay una busqueda-->

<div class="container-fluid" style="margin-left:1%; margin-right:1%;">
<%if @flag==false %>

  <h2 style="color: #2D6F96;">Cotización de monedas</h2>


 <%if @coinrates.count ==0%>
      <center>
        <p class='text-muted'>No hay registros </p>
      </center>
  <%end%>
<%end%>
 <%if @coinrates.count >0%>

  </div>
 <div class="container-fluid" style="margin-left:15%; margin-right:15%;">
    <center>
    <table class="table table-striped">
      <col width="20%">
      <col width="10%">
      <col width="10%">
       <col width="10%">

       <col width="40%">

      <thead>
        <tr>
          <th>A la fecha</th>

          <th>Moneda</th>
             <th>Compra</th>
      <th>Venta</th>


<%if user_signed_in?%>
       <%if current_user.has_role? :admin%>

      <th >Opciones</th>
      <%end%>
  <%end%>
        </tr>
      </thead>
      <tbody>
        <% @coinrates.each do |coinrate| %>
          <tr>
            <td><%= coinrate.todate %></td>
            <td><%= coinrate.ratetype.name %></td>
            <td> <%= coinrate.buy %> Bs.</td>
            <td><%= coinrate.sale %> Bs.</td>
<%if user_signed_in?%>
       <%if current_user.has_role? :admin%>
            <td>
              <div class='btn btn-group'>
                <%= link_to 'Editar', edit_coinrate_path(coinrate), class:'btn btn-xs btn-primary' %>
                <%= link_to 'Eliminar', coinrate, method: :delete, data: { confirm: '¿Está seguro de eliminar?' } , class:'btn btn-xs btn-danger'%>

              </div>
            </td>
            <%end%>
  <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>
     <%= will_paginate @coinrates, renderer: BootstrapPagination::Rails, :previous_label => '<i class="fa fa-arrow-left fa-fw"> </i>', :next_label => '<i class="fa fa-arrow-right fa-fw"> </i>' %><br>
     <%end%>
    <br>
    <%if user_signed_in?%>
       <%if current_user.has_role? :admin%>
       <center>
  <div class="btn btn-group">
    <%= link_to 'Crear cotización', new_exchange_path, class:'btn btn-sm btn-primary' %>
  </div>
</center>
<%end%>
  <%end%>
   </div>
   <!--HASTA esto si es que no hay una busqueda-->
<%= link_to 'Volver', :back, :class=>'btn btn-sm btn-default' %>

app/views/exchanges/new.html.erb
<%  if (user_signed_in?)%>
  <% if current_user.has_role? :admin%>
    <%= render 'form' %>
  <%  end %>
<%  else %>
    <%= render template: 'home/denial' %>
<%  end %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To date:</strong>
  <%= @exchange.to_date %>
</p>

<p>
  <strong>Buy value:</strong>
  <%= @exchange.buy_value %>
</p>

<p>
  <strong>Ratetype:</strong>
  <%= @exchange.ratetype.name %>
</p>

<p>
  <strong>Rateclass:</strong>
  <%= @exchange.rateclass.name %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>