config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/development_rates/:id/edit' => 'development_rates#edit'
  post '/development_rates/:id' => 'development_rates#show'
  resources :topics
  resources :coinrates
  resources :exchanges
  resources :rate_registers
  resources :development_rates
  resources :rates

  resources :countries

  get '/articles/suggested/:id/authorize' => 'articles#authorize'
  get '/articles/suggested/:id/deauthorize' => 'articles#deauthorize'
  get '/articles/suggested' => 'articles#suggested'
  get '/about_us' => 'home#about_us'
  get '/denial' => 'home#denial'

  get '/contact_us' => 'home#contact_us'

  get '/users/show' => 'admin#show'
  get '/users/all'=>'admin#alluser'
  get '/show_user/:id' => 'admin#show_user'
  devise_for :users
  resources :ratetypes
  resources :comments
  resources :rateclasses

  resources :companies
  resources :articles

  get '/new_article' => 'articles#new'
  get '/new_rate' => 'rateclasses#new_rate'
  get '/new_rate' => 'ratetypes#new_rate'
  get '/articles' => 'articles#index'
  get '/articles/:id/comments/new' => 'comments#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments

belongs_to :topic

	validates :title,:description,:content,:author, presence: true
	validates :title, uniqueness: {scope: :author}
	def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%")
  end
end

app/models/coinrate.rb
class Coinrate < ActiveRecord::Base
	validates :ratetype,:sale, :buy ,:todate, presence: true

  belongs_to :ratetype
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
  belongs_to :article
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :nit,:name,:background,:location, presence: true
	validates :name, uniqueness: {message:'ya ha sido utilizado.'}
	validates :nit, uniqueness: {message:'ya ha sido utilizado.'}
	validate :valid_nit?
	has_attached_file :image,:storage => :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml")
	validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
	has_many :users
	has_many :companygoers, :through => :users

	def valid_nit?
		unless self.nit.scan(/[\D]/).empty?
			errors.add(:nit, 'debe contener caracteres numéricos únicamente.')
		end
	end

	def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ? and nit <> ?", "%#{query}%",0)
  end
end

app/models/companygoer.rb
class Companygoer < ActiveRecord::Base
  has_many :users
  has_many :companies, :through => :users
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :rate_registers
  validates :name, :code, presence: true
  validates :name, :code, uniqueness: true
  validates :code, length: {is:3}
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ? or code like ?", "%#{query}%","%#{query}%")
  end
end

app/models/development_rate.rb
class DevelopmentRate < ActiveRecord::Base
  has_many :rate_registers
  validates :name, :description, presence:true
  validates :name, uniqueness:true
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
	validates :ratetype,:saleprice,:to_date, presence: true
  belongs_to :ratetype
  belongs_to :rateclass
  
end

app/models/rate_register.rb
class RateRegister < ActiveRecord::Base
  belongs_to :country
  belongs_to :development_rate
  validates :rate_value, presence:true
  def self.search(initial,final)
    where("date_registered between ? and ?", "%#{initial}%","%#{final}%")
  end

end

app/models/rateclass.rb
class Rateclass < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
	
end

app/models/ratetype.rb
class Ratetype < ActiveRecord::Base
	validates :name, :unit , presence: true
	validates :name, uniqueness: true
	belongs_to :rateclass
	
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :articles

	
	validates :name,presence: true
	validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company
  has_many :comments
  belongs_to :companygoer
  validates :name, :lastname, :address, presence: {message:'es requerido.'}
  validates_length_of :password, minimum: 10, too_short: 'Your password must be at least 10 letters.'
  
  validate :password_complexity

  def password_complexity
    if password.present? and not password.match(/(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end


  before_create :auto_role
  def auto_role
    #if self.email.split('@')[1] == 'hechoenbolivia.com'
    if self.email == 'administrador@hechoenbolivia.com'  
      self.add_role :admin
    else
      self.add_role :user
    end
  end
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ? or lastname like ? or email like ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end

app/controllers/rateclasses_controller.rb
class RateclassesController < ApplicationController
  before_action :set_rateclass, only: [:show, :edit, :update, :destroy]

  # GET /rateclasses
  # GET /rateclasses.json
  def index
    @rateclasses = Rateclass.all
  end

  # GET /rateclasses/1
  # GET /rateclasses/1.json
  def show
  end

  # GET /rateclasses/new
  def new
    @rateclass = Rateclass.new
  end

  # GET /rateclasses/1/edit
  def edit
  end
  def new_rate
     @rateclass = Rateclass.new
     @ratetype = Ratetype.new
  end

  # POST /rateclasses
  # POST /rateclasses.json
  
  def create
    @rateclass = Rateclass.new(rateclass_params)

    respond_to do |format|
      if @rateclass.save
        format.html { redirect_to  rateclasses_path, notice: 'Clase de elemento creada exitosamente' }
        format.json { render :show, status: :created, location: @rateclass }

      else
        format.html { render :new }
        format.json { render json: @rateclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rateclasses/1
  # PATCH/PUT /rateclasses/1.json
  def update
    respond_to do |format|
      if @rateclass.update(rateclass_params)
        format.html { redirect_to rateclasses_path, notice: 'Rateclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @rateclass }
      else
        format.html { render :edit }
        format.json { render json: @rateclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rateclasses/1
  # DELETE /rateclasses/1.json
  def destroy
    @rateclass.destroy
    respond_to do |format|
      format.html { redirect_to rateclasses_url, notice: 'Rateclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rateclass
      @rateclass = Rateclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rateclass_params
      params.require(:rateclass).permit(:name)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "¡Oops! Algo pasó mientras guardabamos la información"

    html = <<-HTML
    <div id="error_explanation">
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rateclasses_helper.rb
module RateclassesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/rateclasses/_form.html.erb
<ul class="nav nav-pills">

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Clases <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Crear Clase', new_rateclass_path %></li>
        <li><%= link_to 'Ver Clases', rateclasses_path %></li>
    </ul>
  </li>
   <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Tipos <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Crear Tipo', new_ratetype_path %></li>
        <li><%= link_to 'Ver Tipos', ratetypes_path %></li>
    </ul>
  </li>
</ul>
<br>
<div class="container-fluid">
<%= form_for(@rateclass) do |f| %>
  <% if @rateclass.errors.any? %>
  <div class="alert alert-danger" role="alert">

    <div id="error_explanation">
      <h4>¡Oops! Algo pasó mientras guardabamos la información:</h4>
      <ul>
      <% @rateclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
</div>
<div class="col-xs-6">
      <p class='text-muted' style="color:#D46A6A;" align="right">
        <i><small>Los campos marcados con (*) son obligatorios.</small>
       </i>
      </p>
    </div>
<div class="container">
<table width="1200">
<tr>
  <td>
  <div class="field">
    <%= f.label :nombre_de_la_clase  %>*<br>
     <div class="col-xs-6">
      <p class='text-muted'>
        Ejemplo: metal, moneda, etc.<br>
      </p>
    </div>
    <br><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <br>
 </td>
 <td>
<img class='img-rounded' src="/assets/clase.jpg" width='300px'>
 </td> </tr>
  <tr><td>
  <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>
    <%= link_to 'Atras', :back, :class=>'btn btn-sm btn-default' %>
<% end %>
</td></tr>
</table>
</div>
</div>
</div>

app/views/rateclasses/edit.html.erb
 <%  if (user_signed_in?)%>
  <% if current_user.has_role? :admin%>
    <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Editar Clase de elemento</h1>
    <%= render 'form' %>
    <br><br>
<%  end %>
 <%  else %>

<%= render template: 'home/denial' %>
  <%  end %>

app/views/rateclasses/index.html.erb
<h1 style=" border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Clases de elementos</h1>

<div class="container-fluid" style="margin-left:15%; margin-right:15%;">
<center>
  <table class="table table-striped">

    <thead>
      <tr>
        <th>Nombre</th>

        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
    <% @rateclasses.each do |rateclass| %>

        <tr>
          <td><%= rateclass.name %></td>

          <td>
            <div class='btn btn-group'>
              <%= link_to 'Editar', edit_rateclass_path(rateclass) , class:'btn btn-xs btn-primary' %>

              <%= link_to 'Borrar', rateclass, method: :delete, data: { confirm: '¿Está seguro que desea borrar esta clase de elemento?' } , class:'btn btn-xs btn-danger'%>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="btn btn-group">
    <%= link_to 'Crear', new_rateclass_path, class:'btn btn-sm btn-success' %>

    <%= link_to 'Volver a Cotizacion',new_exchange_path, :class=>'btn btn-sm btn-default' %>
  </div>
  </center>
</div>

app/views/rateclasses/new.html.erb
 <%  if (user_signed_in?)%>
  <% if current_user.has_role? :admin%>
  <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Clase de elemento</h1>
  <%= render 'form' %>
<%  end %>
 <%  else %>

<%= render template: 'home/denial' %>
  <%  end %>

app/views/rateclasses/new_rate.html.erb
<div class="container">
<table class="table" style=" solid #2D6F96; color: #2D6F96; padding-bottom:7px;">
  <tr>

    <th class="tg-031e">
      <button><%= link_to 'Ver las classes de elementos', rateclasses_path %></button>
<h3 style=" solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Clase de elemento</h3>

   <p id="notice"><%= notice %></p>

      <%= form_for(@rateclass) do |f| %>
  <% if @rateclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rateclass.errors.count, "error") %> no se :</h2>

      <ul>
      <% @rateclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_de_la_clase  %><br>
     <div class="col-xs-6">
      <p class='text-muted'>
        Ejemplo: metal, moneda, etc.<br>
      </p>
    </div>
    <br><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>

  </div>
<% end %>
    </th>
    <th class="tg-031e">
       <button><%= link_to 'Ver los tipos de elementos', ratetypes_path %></button>
      <h3 style=" solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Tipo de elemento</h3>
      <p id="notice"><%= notice %></p>
    <div class="col-xs-6">
      <p class='text-muted'>
        Ejemplo: Euro, Dolar, oro, plata.      </p>
    </div>
    <br><br>
      <%= form_for(@ratetype) do |f| %>
  <% if @ratetype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ratetype.errors.count, "error") %> prohibited this ratetype from being saved:</h2>

      <ul>
      <% @ratetype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unidad_de_medida %><br>
    <div class="col-xs-8">
      <p class='text-muted'>
        Ejemplo: onza, $/onza troy, Bs.
      </p>
    </div>
    <br><br>
    <%= f.text_field :unit %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>

  </div>
<% end %>
    </th>
  </tr>
  <tr>
    <td class="tg-yw4l" colspan="2">
     <h3 style=" solid #2D6F96; color: #2D6F96; padding-bottom:7px;">AQUI SE PODRA CREAR UNA COTIZACION ESCOGIENDO UN TIPO Y UNA CLASE</h3>

    </td>
  </tr>
</table>
</div>

app/views/rateclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rateclass.name %>
</p>

<%= link_to 'Edit', edit_rateclass_path(@rateclass) %> |
<%= link_to 'Back', rateclasses_path %>