config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/development_rates/:id/edit' => 'development_rates#edit'
  post '/development_rates/:id' => 'development_rates#show'
  resources :topics
  resources :coinrates
  resources :exchanges
  resources :rate_registers
  resources :development_rates
  resources :rates

  resources :countries

  get '/articles/suggested/:id/authorize' => 'articles#authorize'
  get '/articles/suggested/:id/deauthorize' => 'articles#deauthorize'
  get '/articles/suggested' => 'articles#suggested'
  get '/about_us' => 'home#about_us'
  get '/denial' => 'home#denial'

  get '/contact_us' => 'home#contact_us'

  get '/users/show' => 'admin#show'
  get '/users/all'=>'admin#alluser'
  get '/show_user/:id' => 'admin#show_user'
  devise_for :users
  resources :ratetypes
  resources :comments
  resources :rateclasses

  resources :companies
  resources :articles

  get '/new_article' => 'articles#new'
  get '/new_rate' => 'rateclasses#new_rate'
  get '/new_rate' => 'ratetypes#new_rate'
  get '/articles' => 'articles#index'
  get '/articles/:id/comments/new' => 'comments#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments

belongs_to :topic

	validates :title,:description,:content,:author, presence: true
	validates :title, uniqueness: {scope: :author}
	def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy,:authorize, :deauthorize]

  # GET /articles
  # GET /articles.json
  def index
    if params[:search]
      @articles = Article.search(params[:search]).where(confirmed:true).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
      
    else
      @articles = Article.where(confirmed:true).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    end
  end

  def suggested
    if params[:search]
      @articles = Article.search(params[:search]).where(suggested:true).order("created_at DESC")
    else
      @articles = Article.where(suggested:true).order("created_at DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
     @comment = Comment.new
     @comments=Comment.all
  end
  def home
  end

  # GET /articles/new
  def new
    @article = Article.new


  end
  def deauthorize
     @article.confirmed=false
     respond_to do |format|
       if @article.save
         format.html { redirect_to '/articles/suggested', notice: 'Artículo editado con éxito' }
         format.json { render :show, status: :ok, location: @article }
       else
         format.html { render :edit }
         format.json { render json: @article.errors, status: :unprocessable_entity }
       end
     end
  end
  def authorize
     @article.confirmed=true
     respond_to do |format|
       if @article.save
         format.html { redirect_to '/articles/suggested', notice: 'Artículo editado con éxito' }
         format.json { render :show, status: :ok, location: @article }
       else
         format.html { render :edit }
         format.json { render json: @article.errors, status: :unprocessable_entity }
       end
     end
  end
  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    if current_user.has_role? :admin
      @article.confirmed=true
    else
      @article.confirmed=false
    end
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Artículo creado con éxito' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Artículo editado con éxito' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Artículo borrado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :author, :description, :confirmed, :suggested, :topic_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
      <%= form_for(@article) do |f| %>
        <% if @article.errors.any? %>
        <div class="alert alert-danger" role="alert">

          <div id="error_explanation">
            <h4>¡Oops! Algo pasó mientras guardabamos la información:</h4>
            <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        </div>
        <% end %>
<div class="row">
  <div class='col-md-8'>
  <div class="field">
    <p class='text-muted'>
    <%= f.label :Título %>*
    <%= f.text_field :title, :size=>'90' %>
  </p>
  </div>
  </div>
  <div class='col-md-4'>
    <%if current_user.has_role? :admin%>
      <div class="field">
        <p class='text-muted' align='center'>
        <%= f.hidden_field :suggested, value:false %>
        <span class="label label-default">Autorizado</span>
        </p>
      </div>
    <%else%>
      <div class="field">
        <p class='text-muted' align='center'>
        <%= f.hidden_field :suggested, value:true %>
        <span class="label label-default"> Autorización pendiente</span>
        </p>
      </div>
    <%end%>
  </div>
</div>
  <div class="field">
    <p class='text-muted'>
    <%= f.label :Autor %>*
    <%= f.text_field :author, :size=>'90' %>
      </p>
  </div>
<div class="field">
    <p class='text-muted'>

  <%= f.label :categoria %>*
     <%= f.collection_select(:topic_id, Topic.all, :id, :name, {:required => "required"}) %>

 </p>
  </div>

  <div class="field">
    <p class='text-muted'>
    <%= f.label :Breve_Descripcion %>*<br>
    <%= f.text_area :description , :size=>"150x7"  %>
      </p>
  </div>
   <div class="field">
    <p class='text-muted'>
    <%= f.label :Contenido %>*<br>
    <%= f.text_area :content , :size => "150x30"  %>
      </p>
  </div>
<center>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-sm btn-success'%>
    <%= link_to 'Atrás', articles_path, :class => 'btn btn-sm btn-default'%>
  </div>
</center>

<% end %>

app/views/articles/edit.html.erb
 <%  if (user_signed_in?)%>
  <% if current_user.has_role? :admin%>
    <h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Editar artículo</h1>
      <%= render 'form' %>
  <%  end %>
 <%  else %>
      <%= render template: 'home/denial' %>
  <%  end %>

app/views/articles/index.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Artículos</h1>


<div class="container-fluid" style="margin-left:1%; margin-right:1%;">


<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Buscar artículo" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn btn-sm" type="submit">Buscar</button>
    </div>
  <% end %>
  </div>
   <%if @articles.count ==0%>
      <center>
        <p class='text-muted'>No hay registros </p>
      </center>
    <%end%>
<table  class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <b>  <%= article.title %> </b><br> <h6> <i> <%= article.author %></i></h6>
          <h6> <p align="justify"><%= article.description %></p></h6>
        </td>
        <td width="100"><%= link_to 'Ver más', article %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= will_paginate @articles, renderer: BootstrapPagination::Rails, :previous_label => '<i class="fa fa-arrow-left fa-fw"> </i>', :next_label => '<i class="fa fa-arrow-right fa-fw"> </i>' %><br>
<br>
<center>
  <div class="btn btn-group">
    <%if user_signed_in?%>
      <%if current_user.has_role? :admin%>
        <%= link_to 'Crear Artículo', new_article_path, class:'btn btn-sm btn-primary' %>
      <% end %>
    <% end %>
      <%= link_to 'Atrás', :back, :class=>'btn btn-sm btn-default' %>
  </div>
  </center>

app/views/articles/new.html.erb
<%  if (user_signed_in?)%>
<% if current_user.has_role? :admin%>


<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Crear Artículo</h1>
<div class="container-fluid">
<div class="row">
    <div class="col-xs-6">
      <p class='text-muted'>
        Rellene los siguientes campos con la información pertinente:<br>
      </p>
    </div>
    <div class="col-xs-6">
      <p class='text-muted' style="color:#D46A6A;" align="right">
        <i><small>Los campos marcados con (*) son obligatorios.</small>
        <br><br></i>
      </p>
    </div>
  </div>
  </div>
<div class="col-xs-4">

    </div>
    <br>


<%= render 'form' %>

<br>
<div class="well well-sm">Caso de uso: Crear Articulo</div>
<%else%>
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Sugerir Artículo</h1>
<div class="container-fluid">
<div class="row">
    <div class="col-xs-6">
      <p class='text-muted'>
        Rellene los siguientes campos con la información pertinente:<br>
      </p>
    </div>
    <div class="col-xs-6">
      <p class='text-muted' style="color:#D46A6A;" align="right">
        <i><small>Los campos marcados con (*) son obligatorios.</small>
        <br><br></i>
      </p>
    </div>
  </div>
  </div>
  <div class="col-xs-4">
  </div>

<%= render 'form' %>
<br>
<%  end %>
<%  else %>

<%= render template: 'home/denial' %>


<%  end %>

app/views/articles/show.html.erb
<p class='text-muted' style="color:#D46A6A;" align="right">
        <i><small><%= notice %></small>
        <br><br></i>
      </p>
  <h1 class="text-center" style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;"><%= @article.title %></h1>
 <h5 class="text-center"><i>Por <%= @article.author %>  </i>
 	<br>
 	<br><%= @article.created_at.strftime( '%x' ) %></h5>
<br>
 <article>
<p align='justify'>
<h5><b>Categoria:  <%= @article.topic.name %></b></h5>
<%=  @article.content.gsub(/\n/,"<br>").html_safe %>
</p>
</article>
<%if user_signed_in?%>
  <%if current_user.has_role? :admin%>
<div class='btn btn-group'>
              <%= link_to 'Editar', edit_article_path(@article), class:'btn btn-sm btn-primary' %>
              <%= link_to 'Borrar', @article, method: :delete, data: { confirm: 'Seguro?' }, class:'btn btn-sm btn-danger'%>
</div>
 <%end%>
 <%end%>


<%= link_to 'Atrás', articles_path %>
<br>
<br>
<b>Comentarios sobre el artículo</b>
<br>

<table class="table table-condensed">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
<% if comment.article_id == @article.id %>
 <tr>
   <td> <b><%= User.find(comment.user_id).name %>: </b><br>

             <%= comment.content %> <br> <br></td>

        <%if user_signed_in?%>
        <%if current_user.id == comment.user_id%>


  <div class='btn btn-group'>
              <td><%= link_to 'Editar', edit_comment_path(comment), class:'btn btn-xs btn-primary' %></td>
              <td><%= link_to 'Borrar', comment, method: :delete, data: { confirm: '¿Seguro que desea eliminar este comentario?' }, class:'btn btn-xs btn-danger'%></td>
</div>
     <%end%>
      <%end%>
      </tr>
       <%end%>
    <% end %>
  </tbody>
</table>
  <%if user_signed_in?%>

<%= form_for(@comment) do |f| %>
<div class="field">
    <%= f.label :Comentario %><br>
    <%= f.text_area :content , :size => "150x6"  %>
  </div>
  <%= f.hidden_field :article_id, :value => @article.id %>
   <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit 'Comentar', :class => 'btn btn-sm btn-success'%>
  </div>
 <%end%>
    <% end %>
<br>

app/views/articles/suggested.html.erb
<h1 style="border-bottom: 1px solid #2D6F96; color: #2D6F96; padding-bottom:7px;">Artículos Sugeridos</h1>
<br><br>

<div class="container-fluid" style="margin-left:1%; margin-right:1%;">


<%= form_tag('/articles/suggested', :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Buscar artículo" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn btn-sm" type="submit">Buscar</button>
    </div>
  <% end %>
  </div>
<table  class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><b>  <%= article.title %> </b><%if article.confirmed==true%><span class="label label-primary"> Autorizado</span><%else%><span class="label label-default"> Autorización pendiente</span>
<%end%>

          <br> <h6> <i> <%= article.author %></i></h6>
          <h6> <p align="justify"><%= article.description %> <%= link_to 'Ver más...', article %></p></h6>
        </td>
        <td width="100">
          <%if article.confirmed==false%>
          <%= link_to 'Autorizar', '/articles/suggested/'+article.id.to_s+'/authorize', :class=>'btn btn-xs btn-primary' %>
          <%else%>
          <%= link_to 'Desautorizar', '/articles/suggested/'+article.id.to_s+'/deauthorize', :class=>'btn btn-xs btn-danger' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<center>
  <div class="btn btn-group">
  <%= link_to 'Atrás', :back, :class=>'btn btn-sm btn-default' %>
  </div>
  </center>